let stream,ws,peers=new Map(),pendingIce=new Map();const $=x=>document.getElementById(x);
const T={ru:{settings:'Настройки',source:'Источник',resolution:'Разрешение',fps:'FPS',bitrate:'Битрейт',port:'Порт',pin:'PIN',pinOptional:'необязательно',audio:'Системный звук',start:'Запустить',stop:'Стоп',preview:'Предпросмотр',stopped:'Остановлено',active:'Трансляция активна',receivers:'Подключённые ПК',none:'Нет подключений',copy:'Ссылка скопирована',error:'Ошибка: '},en:{settings:'Settings',source:'Source',resolution:'Resolution',fps:'FPS',bitrate:'Bitrate',port:'Port',pin:'PIN',pinOptional:'optional',audio:'System audio',start:'Start',stop:'Stop',preview:'Preview',stopped:'Stopped',active:'Streaming active',receivers:'Connected PCs',none:'No connections',copy:'Link copied',error:'Error: '}};
let lang=localStorage.getItem('lang')||'ru';
function applyLang(){const t=T[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t[e.dataset.i18n]||e.textContent);document.querySelectorAll('[data-placeholder]').forEach(e=>e.placeholder=t[e.dataset.placeholder]||e.placeholder);$('lang').textContent=lang==='ru'?'EN':'RU';if(!$('state').dataset.running)$('state').textContent=t.stopped;render(window._receivers||[])}
$('lang').onclick=()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('lang',lang);applyLang()};
async function init(){const c=await api.loadConfig();$('p').value=c.port||8080;$('r').value=c.resolution||'1920x1080';$('f').value=c.fps||60;$('b').value=c.bitrate||20000000;$('a').checked=!!c.audio;$('pin').value=c.pin||'';const ss=await api.getSources();ss.forEach(x=>{let o=document.createElement('option');o.value=x.id;o.textContent=x.name;$('s').appendChild(o)});if(ss[0])api.selectSource(ss[0].id);api.onEvent(m=>{if(m.type==='receivers'){window._receivers=m.receivers;render(m.receivers);m.receivers.forEach(x=>offer(x.id))}else if(m.type==='receiver-joined'){window._receivers=[...(window._receivers||[]).filter(x=>x.id!==m.receiver.id),m.receiver];render(window._receivers);offer(m.receiver.id)}else if(m.type==='receiver-left'){window._receivers=(window._receivers||[]).filter(x=>x.id!==m.receiverId);render(window._receivers);peers.get(m.receiverId)?.close();peers.delete(m.receiverId);pendingIce.delete(m.receiverId)}if(m.type==='receiver-signal')signal(m.receiverId,m.payload)});applyLang()}
function cfg(){return{port:+$('p').value,resolution:$('r').value,fps:+$('f').value,bitrate:+$('b').value,audio:$('a').checked,pin:$('pin').value,autoStart:false}}
async function start(){try{let c=cfg();await api.saveConfig(c);await api.selectSource($('s').value);let x=await api.start(c);$('url').textContent=x.url;$('qr').src=x.qr;const [w,h]=c.resolution.split('x').map(Number);stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:w,max:w},height:{ideal:h,max:h},frameRate:{ideal:c.fps,max:c.fps}},audio:c.audio});$('v').srcObject=stream;ws=new WebSocket(`ws://127.0.0.1:${c.port}/signal`);ws.onopen=()=>ws.send(JSON.stringify({type:'join',role:'host'}));$('state').dataset.running='1';$('state').textContent=T[lang].active;$('start').disabled=true;$('stop').disabled=false}catch(e){alert(T[lang].error+(e.message||e))}}
function send(id,p){if(ws?.readyState===1)ws.send(JSON.stringify({receiverId:id,payload:p}))}
async function offer(id){if(!stream||!ws||ws.readyState!==1)return;peers.get(id)?.close();pendingIce.set(id,[]);let pc=new RTCPeerConnection({iceServers:[]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>e.candidate&&send(id,{type:'ice',candidate:e.candidate});pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState)&&peers.get(id)===pc){peers.delete(id);pendingIce.delete(id)}};peers.set(id,pc);await pc.setLocalDescription(await pc.createOffer());send(id,{type:'offer',sdp:pc.localDescription})}
async function signal(id,m){let pc=peers.get(id);if(!pc)return;if(m.type==='answer'){await pc.setRemoteDescription(m.sdp);const q=pendingIce.get(id)||[];pendingIce.delete(id);for(const c of q)try{await pc.addIceCandidate(c)}catch{}}else if(m.type==='ice'&&m.candidate){if(pc.remoteDescription)try{await pc.addIceCandidate(m.candidate)}catch{}else{const q=pendingIce.get(id)||[];q.push(m.candidate);pendingIce.set(id,q)}}}
function render(a){$('count').textContent=a.length;$('list').innerHTML=a.length?a.map(x=>`<div class="receiver">● <b>${esc(x.name)}</b> — ${esc(x.ip)}</div>`).join(''):T[lang].none}function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function stop(){peers.forEach(p=>p.close());peers.clear();pendingIce.clear();if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(ws)ws.close();ws=null;await api.stop();delete $('state').dataset.running;$('state').textContent=T[lang].stopped;$('start').disabled=false;$('stop').disabled=true}
$('start').onclick=start;$('stop').onclick=stop;init();