/* 1.8.6 diagnostic instrumentation: capture, track, WebRTC and runtime health. */
(function(){
'use strict';
const apiLog=(level,message,data)=>{try{window.api?.log?.(level,message,data)}catch{}};
const now=()=>new Date().toISOString();
const safe=v=>{try{return JSON.parse(JSON.stringify(v))}catch{return String(v)}};
const originalConsole={error:console.error.bind(console),warn:console.warn.bind(console),debug:console.debug.bind(console)};
console.error=(...a)=>{originalConsole.error(...a);apiLog('ERROR','Renderer console.error',{args:a.map(safe)})};
console.warn=(...a)=>{originalConsole.warn(...a);apiLog('WARN','Renderer console.warn',{args:a.map(safe)})};
console.debug=(...a)=>{originalConsole.debug(...a);const text=a.map(x=>typeof x==='string'?x:String(x)).join(' ');if(/failed|error|constraint|stats|resolution|track|encoder|sender/i.test(text))apiLog('DEBUG','Renderer console.debug',{message:text,args:a.map(safe)})};
function browserSnapshot(){return{timestamp:now(),userAgent:navigator.userAgent,platform:navigator.platform,language:navigator.language,hardwareConcurrency:navigator.hardwareConcurrency||null,deviceMemory:navigator.deviceMemory||null,devicePixelRatio:window.devicePixelRatio||1,screen:{width:screen.width,height:screen.height,availWidth:screen.availWidth,availHeight:screen.availHeight},window:{innerWidth:window.innerWidth,innerHeight:window.innerHeight},visibility:document.visibilityState}}
apiLog('INFO','Diagnostics instrumentation initialized',browserSnapshot());
if(navigator.mediaDevices?.getDisplayMedia){const originalGetDisplayMedia=navigator.mediaDevices.getDisplayMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getDisplayMedia=async function(constraints){const requestId=`cap-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;apiLog('INFO','CAPTURE_REQUESTED',{requestId,constraints:safe(constraints),timestamp:now()});try{const stream=await originalGetDisplayMedia(constraints);const tracks=stream.getVideoTracks();const audioTracks=stream.getAudioTracks();apiLog('INFO','CAPTURE_CREATED',{requestId,streamId:stream.id,videoTracks:tracks.length,audioTracks:audioTracks.length});tracks.forEach((track,index)=>instrumentTrack(track,requestId,index));return stream}catch(error){apiLog('ERROR','CAPTURE_FAILED',{requestId,error:error?.stack||error?.message||String(error),name:error?.name||'',constraints:safe(constraints)});throw error}}}
function trackSnapshot(track){let settings={},capabilities={},constraints={};try{settings=track.getSettings?.()||{}}catch{}try{capabilities=track.getCapabilities?.()||{}}catch{}try{constraints=track.getConstraints?.()||{}}catch{}return{id:track.id,kind:track.kind,label:track.label,readyState:track.readyState,muted:track.muted,contentHint:track.contentHint||'',settings:safe(settings),capabilities:safe(capabilities),constraints:safe(constraints)}}
function instrumentTrack(track,requestId,index){apiLog('INFO','CAPTURE_TRACK_CREATED',{requestId,index,track:trackSnapshot(track)});track.addEventListener('ended',()=>apiLog('WARN','CAPTURE_TRACK_ENDED',{requestId,index,track:trackSnapshot(track)}));track.addEventListener('mute',()=>apiLog('WARN','CAPTURE_TRACK_MUTED',{requestId,index,track:trackSnapshot(track)}));track.addEventListener('unmute',()=>apiLog('INFO','CAPTURE_TRACK_UNMUTED',{requestId,index,track:trackSnapshot(track)}));if(track.applyConstraints&&!track.__lanDiagWrapped){const originalApply=track.applyConstraints.bind(track);track.applyConstraints=async function(constraints){apiLog('INFO','TRACK_CONSTRAINTS_REQUESTED',{trackId:track.id,constraints:safe(constraints),before:trackSnapshot(track)});try{const result=await originalApply(constraints);apiLog('INFO','TRACK_CONSTRAINTS_APPLIED',{trackId:track.id,after:trackSnapshot(track)});return result}catch(error){apiLog('ERROR','TRACK_CONSTRAINTS_FAILED',{trackId:track.id,constraints:safe(constraints),error:error?.stack||error?.message||String(error),after:trackSnapshot(track)});throw error}};track.__lanDiagWrapped=true}}
const OriginalPC=window.RTCPeerConnection;
if(OriginalPC&&!OriginalPC.__lanDiagWrapped){function DiagnosticPC(...args){const pc=new OriginalPC(...args);const id=`pc-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;pc.__lanDiagId=id;apiLog('INFO','WEBRTC_PC_CREATED',{pcId:id,configuration:safe(args[0]||{})});const wrapEvent=name=>{pc.addEventListener(name,()=>apiLog('INFO',`WEBRTC_${name.toUpperCase()}`,{pcId:id,state:pc[name+'State']||null,connectionState:pc.connectionState,iceConnectionState:pc.iceConnectionState,signalingState:pc.signalingState}))};['connectionstatechange','iceconnectionstatechange','signalingstatechange'].forEach(wrapEvent);pc.addEventListener('icecandidateerror',e=>apiLog('WARN','WEBRTC_ICE_CANDIDATE_ERROR',{pcId:id,address:e.address,port:e.port,url:e.url,errorCode:e.errorCode,errorText:e.errorText}));const originalAddTrack=pc.addTrack.bind(pc);pc.addTrack=function(track,...streams){apiLog('INFO','WEBRTC_TRACK_ADDED',{pcId:id,track:trackSnapshot(track),streamIds:streams.map(s=>s.id)});return originalAddTrack(track,...streams)};const originalCreateOffer=pc.createOffer.bind(pc);pc.createOffer=async function(...a){apiLog('DEBUG','WEBRTC_CREATE_OFFER',{pcId:id,options:safe(a[0]||{})});try{const offer=await originalCreateOffer(...a);apiLog('DEBUG','WEBRTC_OFFER_CREATED',{pcId:id,sdpLength:offer?.sdp?.length||0});return offer}catch(error){apiLog('ERROR','WEBRTC_CREATE_OFFER_FAILED',{pcId:id,error:error?.stack||error?.message||String(error)});throw error}};const originalSetLocal=pc.setLocalDescription.bind(pc);pc.setLocalDescription=async function(desc){apiLog('DEBUG','WEBRTC_SET_LOCAL_DESCRIPTION',{pcId:id,type:desc?.type||'',sdpLength:desc?.sdp?.length||0});try{return await originalSetLocal(desc)}catch(error){apiLog('ERROR','WEBRTC_SET_LOCAL_DESCRIPTION_FAILED',{pcId:id,error:error?.stack||error?.message||String(error)});throw error}};const originalSetRemote=pc.setRemoteDescription.bind(pc);pc.setRemoteDescription=async function(desc){apiLog('DEBUG','WEBRTC_SET_REMOTE_DESCRIPTION',{pcId:id,type:desc?.type||'',sdpLength:desc?.sdp?.length||0});try{return await originalSetRemote(desc)}catch(error){apiLog('ERROR','WEBRTC_SET_REMOTE_DESCRIPTION_FAILED',{pcId:id,error:error?.stack||error?.message||String(error)});throw error}};const originalClose=pc.close.bind(pc);pc.close=function(){apiLog('INFO','WEBRTC_PC_CLOSING',{pcId:id,connectionState:pc.connectionState,iceConnectionState:pc.iceConnectionState});return originalClose()};return pc}DiagnosticPC.prototype=OriginalPC.prototype;Object.setPrototypeOf(DiagnosticPC,OriginalPC);DiagnosticPC.__lanDiagWrapped=true;window.RTCPeerConnection=DiagnosticPC}
let statsTimer=null;function runtimeHealth(){const memory=performance.memory?{usedJSHeapSize:performance.memory.usedJSHeapSize,totalJSHeapSize:performance.memory.totalJSHeapSize,jsHeapSizeLimit:performance.memory.jsHeapSizeLimit}:null;apiLog('STAT','Renderer runtime health',{timestamp:now(),memory,documentVisibility:document.visibilityState,devicePixelRatio:window.devicePixelRatio||1,window:{width:innerWidth,height:innerHeight},screen:{width:screen.width,height:screen.height},hardwareConcurrency:navigator.hardwareConcurrency||null})}
statsTimer=setInterval(runtimeHealth,10000);window.addEventListener('beforeunload',()=>{clearInterval(statsTimer);apiLog('INFO','Renderer unloading',browserSnapshot())});
})();
