let ws=null,pc=null,pendingIce=[],reconnectTimer=null,manualClose=false;const v=document.getElementById('view'),bar=document.getElementById('bar'),err=document.getElementById('err');
function send(x){if(ws?.readyState===1)ws.send(JSON.stringify(x))}
function setStatus(x){bar.textContent=x}
function cleanupPeer(){if(pc){try{pc.close()}catch{}pc=null}pendingIce=[];if(v.srcObject){try{v.srcObject.getTracks().forEach(t=>t.stop())}catch{}v.srcObject=null}}
function scheduleReconnect(){if(manualClose||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect(true)},1500)}
function connect(retry=false){manualClose=false;err.textContent='';if(!retry){cleanupPeer();if(ws)try{ws.close()}catch{};ws=null}const name=(document.getElementById('name').value||'Browser').slice(0,40),pin=document.getElementById('pin').value;setStatus('Подключение к источнику…');ws=new WebSocket((location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+'/signal');
ws.onopen=()=>{send({type:'join',role:'receiver',name,pin});setStatus('Ожидание потока…')};
ws.onmessage=async e=>{let m;try{m=JSON.parse(e.data)}catch{return};if(m.type==='auth-error'){err.textContent=m.message||'Доступ запрещён';manualClose=true;try{ws.close()}catch{}return}
if(m.type==='offer')await handleOffer(m);if(m.type==='ice'&&m.candidate){if(pc&&pc.remoteDescription)try{await pc.addIceCandidate(m.candidate)}catch{}else pendingIce.push(m.candidate)}};
ws.onerror=()=>{if(!manualClose)err.textContent='Не удалось подключиться к серверу'};ws.onclose=()=>{if(!manualClose){setStatus('Соединение потеряно — переподключение…');scheduleReconnect()}else setStatus('Соединение закрыто')};}
async function handleOffer(m){try{if(pc)cleanupPeer();pc=new RTCPeerConnection({iceServers:[]});pc.ontrack=e=>{if(!v.srcObject)v.srcObject=new MediaStream();if(!v.srcObject.getTracks().includes(e.track))v.srcObject.addTrack(e.track);v.play().catch(()=>{});document.getElementById('join').style.display='none';setStatus('Подключено')};pc.onicecandidate=e=>{if(e.candidate)send({type:'ice',candidate:e.candidate})};pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==='connected')setStatus('Подключено');else if(['failed','disconnected','closed'].includes(s)){setStatus('Соединение потеряно — переподключение…');scheduleReconnect()}};await pc.setRemoteDescription(m.sdp);const queued=pendingIce.splice(0);for(const c of queued)try{await pc.addIceCandidate(c)}catch{}const a=await pc.createAnswer();await pc.setLocalDescription(a);send({type:'answer',sdp:pc.localDescription})}catch(e){err.textContent='WebRTC: '+(e.message||e);scheduleReconnect()}}
document.getElementById('go').onclick=()=>connect(false);document.getElementById('full').onclick=()=>v.requestFullscreen().catch(()=>document.documentElement.requestFullscreen().catch(()=>{}));document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='f')document.getElementById('full').click()});window.addEventListener('beforeunload',()=>{manualClose=true;try{ws?.close()}catch{}cleanupPeer()});