const {app,BrowserWindow,desktopCapturer,session,screen,ipcMain}=require('electron');
const path=require('path'),os=require('os'),fs=require('fs'),express=require('express'),http=require('http'),WebSocket=require('ws'),QRCode=require('qrcode');
let win,server,wss,port=8080,selectedSourceId,receivers=new Map();
const cfgPath=()=>path.join(app.getPath('userData'),'config.json');
function load(){try{return JSON.parse(fs.readFileSync(cfgPath(),'utf8'))}catch{return{port:8080,resolution:'1920x1080',fps:60,bitrate:20000000,audio:false,autoStart:false,pin:''}}}
function save(c){fs.mkdirSync(path.dirname(cfgPath()),{recursive:true});fs.writeFileSync(cfgPath(),JSON.stringify(c,null,2))}
function ip(){for(const a of Object.values(os.networkInterfaces()))for(const n of a||[])if(n.family==='IPv4'&&!n.internal)return n.address;return'127.0.0.1'}
function list(){return[...receivers.values()].map(x=>x.info)}
function event(x){win?.webContents.send('server-event',x)}
async function startServer(p){const ex=express();ex.disable('x-powered-by');ex.use(express.static(path.join(__dirname,'..','web','receiver')));server=http.createServer(ex);wss=new WebSocket.Server({server,path:'/signal'});wss.on('connection',(ws,req)=>{const rip=(req.socket.remoteAddress||'').replace(/^::ffff:/,'');let id=null;let role='';ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='join'){role=m.role;if(role==='receiver'){id=Date.now()+'-'+Math.random().toString(36).slice(2);const info={id,name:String(m.name||'Browser').slice(0,40),ip:rip};receivers.set(id,{ws,info});ws.send(JSON.stringify({type:'joined',id}));event({type:'receivers',receivers:list()})}return}if(role==='receiver'&&id)event({type:'receiver-signal',receiverId:id,payload:m});if(role==='host'&&m.receiverId){const r=receivers.get(m.receiverId);if(r?.ws.readyState===WebSocket.OPEN)r.ws.send(JSON.stringify(m.payload))}});ws.on('close',()=>{if(id){receivers.delete(id);event({type:'receivers',receivers:list()})}})});await new Promise((res,rej)=>{server.once('error',rej);server.listen(p,'0.0.0.0',res)})}
async function stop(){for(const r of receivers.values())try{r.ws.close()}catch{}receivers.clear();try{wss?.close()}catch{}if(server)await new Promise(r=>server.close(r));server=null;wss=null}
function create(){win=new BrowserWindow({width:1120,height:820,backgroundColor:'#0d1015',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'..','web','host','index.html'))}
app.whenReady().then(()=>{session.defaultSession.setDisplayMediaRequestHandler(async(_r,cb)=>{const s=await desktopCapturer.getSources({types:['screen','window'],thumbnailSize:{width:0,height:0}});cb({video:s.find(x=>x.id===selectedSourceId)||s[0]})});ipcMain.handle('sources',async()=>{const s=await desktopCapturer.getSources({types:['screen','window'],thumbnailSize:{width:240,height:135}});return s.map(x=>({id:x.id,name:x.name,display_id:x.display_id,thumbnail:x.thumbnail.toDataURL()}))});ipcMain.handle('config-load',load);ipcMain.handle('config-save',(_e,c)=>{save(c);return true});ipcMain.handle('select-source',(_e,id)=>{selectedSourceId=id;return true});ipcMain.handle('start-server',async(_e,c)=>{await stop();port=Number(c.port);save(c);await startServer(port);const u=`http://${ip()}:${port}/`;return{url:u,ip:ip(),port,qr:await QRCode.toDataURL(u)}});ipcMain.handle('stop-server',stop);create()});
app.on('window-all-closed',async()=>{await stop();if(process.platform!=='darwin')app.quit()});
