const {app,BrowserWindow,desktopCapturer,session,ipcMain,Tray,Menu}=require('electron');
const path=require('path'),os=require('os'),fs=require('fs'),{execFile}=require('child_process'),express=require('express'),http=require('http'),WebSocket=require('ws'),QRCode=require('qrcode');
let win,server,wss,port=8080,selectedSourceId,hostWs=null,receivers=new Map(),blockedReceivers=new Set(),currentConfig={pin:''},tray=null,forceQuit=false;
const resource=p=>app.isPackaged?path.join(process.resourcesPath,p):path.join(__dirname,'..',p);
const cfgPath=()=>path.join(app.getPath('userData'),'config.json');
function load(){try{return JSON.parse(fs.readFileSync(cfgPath(),'utf8'))}catch{return{port:8080,resolution:'1920x1080',fps:60,bitrate:20000000,audio:false,autoStart:false,pin:''}}}
function save(c){fs.mkdirSync(path.dirname(cfgPath()),{recursive:true});fs.writeFileSync(cfgPath(),JSON.stringify(c,null,2));currentConfig=c}
function isPrivate(ip){const p=String(ip||'').split('.').map(Number);return p.length===4&&((p[0]===10)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168))}
function interfaces(){const out=[];for(const [name,list] of Object.entries(os.networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal&&isPrivate(n.address))out.push({name,address:n.address,netmask:n.netmask||''});return out}
function preferredLanIp(){return new Promise(resolve=>{if(process.platform!=='win32')return resolve(interfaces()[0]?.address||'127.0.0.1');const ps="$c=Get-NetIPConfiguration | Where-Object {$_.IPv4DefaultGateway -and $_.IPv4Address} | ForEach-Object { [PSCustomObject]@{Alias=$_.InterfaceAlias;Address=$_.IPv4Address.IPAddress;Gateway=$_.IPv4DefaultGateway.NextHop;Metric=$_.InterfaceMetric} }; $c | ConvertTo-Json -Compress";execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',ps],{windowsHide:true},(err,out)=>{if(!err&&out){try{let a=JSON.parse(out);if(!Array.isArray(a))a=[a];const good=a.filter(x=>isPrivate(x.Address)&&x.Gateway);const rank=x=>{const s=String(x.Alias||'').toLowerCase();return (s.includes('ethernet')?0:s.includes('wi-fi')||s.includes('wifi')?1:s.includes('wireless')?2:10)};good.sort((a,b)=>rank(a)-rank(b)||(Number(a.Metric)||999)-(Number(b.Metric)||999));if(good[0])return resolve(good[0].Address)}catch{}}const fallback=interfaces();const preferred=fallback.find(x=>/ethernet|wi-fi|wifi|wireless/i.test(x.name))||fallback[0];resolve(preferred?.address||'127.0.0.1')})})}
function list(){return[...receivers.values()].map(x=>x.info)}function event(x){win?.webContents.send('server-event',x)}function send(ws,m){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(m))}
function addFirewallRule(p){return new Promise(resolve=>{const name=`LAN Desktop Stream TCP ${p}`;const script=`$n='${name.replace(/'/g,"''")}'; $old=Get-NetFirewallRule -DisplayName $n -ErrorAction SilentlyContinue; if($old){Set-NetFirewallRule -DisplayName $n -Enabled True -Profile Private -Action Allow}else{New-NetFirewallRule -DisplayName $n -Direction Inbound -Protocol TCP -LocalPort ${Number(p)} -Action Allow -Profile Private | Out-Null}`;execFile('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{windowsHide:true},err=>resolve(!err))})}
async function startServer(p){const ex=express();ex.disable('x-powered-by');ex.use(express.static(path.join(__dirname,'..','web','receiver')));const nextServer=http.createServer(ex);const nextWss=new WebSocket.Server({server:nextServer,path:'/signal'});nextWss.on('connection',(ws,req)=>{const rip=(req.socket.remoteAddress||'').replace(/^::ffff:/,'');let id=null,role='',clientId='';ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return};if(m.type==='join'){role=m.role;if(role==='host'){if(hostWs&&hostWs!==ws)try{hostWs.close(1000,'Replaced by new host')}catch{}hostWs=ws;send(ws,{type:'host-ready'});for(const r of receivers.values())send(ws,{type:'receiver-joined',receiver:r.info});return}if(role==='receiver'){clientId=String(m.clientId||'').slice(0,128);if(!clientId){send(ws,{type:'kicked',message:'Не удалось определить идентификатор приёмника'});try{ws.close(4003,'Missing client id')}catch{}return}if(blockedReceivers.has(clientId)){send(ws,{type:'kicked',message:'Этот приёмник отключён источником'});try{ws.close(4000,'Receiver blocked by host')}catch{}return}const wantedPin=String(m.pin||'');if(currentConfig.pin&&wantedPin!==String(currentConfig.pin)){send(ws,{type:'auth-error',message:'Неверный PIN'});setTimeout(()=>{try{ws.close()}catch{};},300);return}id=Date.now()+'-'+Math.random().toString(36).slice(2,10);const info={id,clientId,name:String(m.name||'Browser').slice(0,40),ip:rip};receivers.set(id,{ws,info});send(ws,{type:'joined',id});event({type:'receivers',receivers:list()});send(hostWs,{type:'receiver-joined',receiver:info})}return}if(role==='receiver'&&id)send(hostWs,{type:'receiver-signal',receiverId:id,payload:m});else if(role==='host'&&m.receiverId){const r=receivers.get(m.receiverId);send(r?.ws,m.payload)}});ws.on('close',()=>{if(ws===hostWs)hostWs=null;if(id){receivers.delete(id);event({type:'receivers',receivers:list()});send(hostWs,{type:'receiver-left',receiverId:id})}})});
server=nextServer;wss=nextWss;
await new Promise((res,rej)=>{let settled=false;const onError=err=>{if(settled)return;settled=true;nextServer.removeListener('listening',onListen);rej(err)};const onListen=()=>{if(settled)return;settled=true;nextServer.removeListener('error',onError);res()};nextServer.once('error',onError);nextServer.once('listening',onListen);nextServer.listen(p,'0.0.0.0')});
}
async function closeWebSockets(){const sockets=[];if(wss){for(const c of wss.clients||[])sockets.push(c);for(const c of sockets){try{c.close(1001,'Server stopping')}catch{}try{if(c.readyState!==WebSocket.CLOSED)c.terminate()}catch{}}await new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};try{wss.close(finish)}catch{finish()}setTimeout(finish,1000)})}if(hostWs){try{hostWs.close()}catch{}try{hostWs.terminate()}catch{}hostWs=null}}
async function stop(){for(const r of receivers.values()){try{r.ws.close(4001,'Server stopping')}catch{}try{r.ws.terminate()}catch{}}receivers.clear();event({type:'receivers',receivers:[]});await closeWebSockets();const s=server;server=null;wss=null;if(s){try{if(typeof s.closeAllConnections==='function')s.closeAllConnections()}catch{}await new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};try{s.close(finish)}catch{finish()}setTimeout(finish,1500)})}}
function create(){win=new BrowserWindow({width:1120,height:820,backgroundColor:'#0d1015',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'..','web','host','index.html'));win.on('close',e=>{if(!forceQuit){e.preventDefault();win.hide()}});win.on('closed',()=>{win=null})}
function createTray(){const icon=resource('app_icon_monitor.ico');try{tray=new Tray(icon);tray.setToolTip('LAN Desktop Stream');tray.setContextMenu(Menu.buildFromTemplate([{label:'Показать LAN Desktop Stream',click:()=>{if(!win)return;win.show();win.restore();win.focus()}},{type:'separator'},{label:'Выход',click:()=>{forceQuit=true;stop().finally(()=>{tray?.destroy();app.exit(0)})}}]));tray.on('double-click',()=>{win?.show();win?.restore();win?.focus()})}catch(e){console.error('Tray initialization failed:',e)}}
app.whenReady().then(()=>{currentConfig=load();session.defaultSession.setDisplayMediaRequestHandler(async(_r,cb)=>{const s=await desktopCapturer.getSources({types:['screen','window'],thumbnailSize:{width:0,height:0}});cb({video:s.find(x=>x.id===selectedSourceId)||s[0]})});ipcMain.handle('sources',async()=>{const s=await desktopCapturer.getSources({types:['screen','window'],thumbnailSize:{width:240,height:135}});return s.map(x=>({id:x.id,name:x.name,display_id:x.display_id,thumbnail:x.thumbnail.toDataURL()}))});ipcMain.handle('config-load',load);ipcMain.handle('config-save',(_e,c)=>{save(c);return true});ipcMain.handle('select-source',(_e,id)=>{selectedSourceId=id;return true});ipcMain.handle('start-server',async(_e,c)=>{await stop();blockedReceivers.clear();port=Number(c.port);save(c);await startServer(port);const firewallAdded=await addFirewallRule(port);const hostIp=await preferredLanIp();const hostname=os.hostname();const u=`http://${hostIp}:${port}/`;return{url:u,ip:hostIp,hostname,port,qr:await QRCode.toDataURL(u),firewallAdded}});ipcMain.handle('disconnect-receiver',(_e,id)=>{const key=String(id),r=receivers.get(key);if(!r)return false;blockedReceivers.add(String(r.info.clientId));try{r.ws.close(4000,'Disconnected by host')}catch{}try{r.ws.terminate()}catch{}receivers.delete(key);event({type:'receivers',receivers:list()});send(hostWs,{type:'receiver-left',receiverId:key});return true});ipcMain.handle('stop-server',stop);ipcMain.handle('network-info',async()=>({ip:await preferredLanIp(),hostname:os.hostname(),interfaces:interfaces()}));create();createTray()});
app.on('window-all-closed',()=>{});
app.on('before-quit',()=>{forceQuit=true});
